# Generated by Django 5.2.8 on 2025-11-22 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('category', models.CharField(choices=[('user_missed_habit', 'User Missed Habit'), ('partner_missed_habit', 'Partner Missed Habit'), ('streak_milestone', 'Streak Milestone'), ('routine_completed', 'Routine Completed'), ('partnership_request', 'Partnership Request'), ('partnership_request_accepted', 'Partnership Request Accepted'), ('partnership_request_rejected', 'Partnership Request Rejected')], max_length=50, verbose_name='Category')),
                ('read_status', models.BooleanField(default=False, verbose_name='Read Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
                ('trigger_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_notifications', to='habits.action')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['user_missed_habit', 'partner_missed_habit', 'streak_milestone']), _negated=True), ('trigger_action__isnull', False), _connector='OR'), name='habit_trigger_is_action_and_action_exists'), models.CheckConstraint(condition=models.Q(models.Q(('category__startswith', 'partnership'), _negated=True), ('trigger_action__isnull', True), _connector='OR'), name='partnership_request_does_not_have_trigger_action'), models.CheckConstraint(condition=models.Q(models.Q(('category', 'partnership'), _negated=True), ('created_by__isnull', False), _connector='OR'), name='partnership_request_has_a_created_by_user')],
            },
        ),
    ]
