# Generated by Django 5.2.8 on 2025-11-21 19:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Routine Name')),
                ('reason', models.TextField(help_text='Why is this routine important to you?', max_length=500, verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('target_completions', models.PositiveIntegerField(default=30, help_text='Number of Completions before check in starts', verbose_name='Target Completions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Action Name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20, verbose_name='Frequency')),
                ('start_time', models.TimeField(help_text='What time do you plan to do this habit?', verbose_name='Start Time')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Current Streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Longest Streak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='habits.routine')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(default=datetime.date.today, verbose_name='Completed At')),
                ('difficulty', models.PositiveSmallIntegerField(default=5, help_text='How difficulty was this?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Difficulty')),
                ('confidence', models.PositiveSmallIntegerField(default=5, help_text='How confident are you that you will keep it up?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Confidence')),
                ('feeling', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('struggled', 'Struggled'), ('forced', 'Forced')], default='okay', max_length=20, verbose_name='Feeling')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_records', to='habits.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit Completion',
                'verbose_name_plural': 'Habit Completions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('action', 'completion_date'), name='one_completion_per_action_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='end_date_after_start_date'),
        ),
    ]
