# Generated by Django 5.2.8 on 2025-11-21 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_accountability_partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_accountable_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accountability Partnership',
                'verbose_name_plural': 'Accountability Partnerships',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'accepted'])), fields=('user', 'partner'), name='unique_active_partnership')],
            },
        ),
    ]
